### ISSUE TITLE
Çalışmıyor

### ISSUE THREAD

**Issue by ByJacoB27** [usameavci/papara-sdk#1]
Hocam bir kaç test yaptım ama başarılı olmadı. bu olay haricin de sistemin kendi dısından api.parapara.com üzerinden yapabileceğimiz şeyler var mı ?

**Comment by usameavci** [comment]
@ByJacoB27 Çok eski bir paket bu, yanlış bilmiyorsam papara ben bu paketi yazdıktan sonra 2-3 kez api update etti. Şu anda çalışmaması normal :) Bu repo gözüme çarpmadığı için arşivlememişim. Papara şu anda api dökümantasyonunu özel olarak veriyor o yüzden paketi güncelleyemeyeceğim maalesef.
